// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vscode = require("vscode");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var left = Vscode.StatusBarAlignment.Left;

var right = Vscode.StatusBarAlignment.Right;

var StatusBarAlignment = {
  left: left,
  right: right
};

var block = Vscode.TextEditorCursorStyle.Block;

var line = Vscode.TextEditorCursorStyle.Line;

var TextEditorCursorStyle = {
  block: block,
  line: line
};

var atTop = Vscode.TextEditorRevealType.AtTop;

var $$default = Vscode.TextEditorRevealType.Default;

var inCenter = Vscode.TextEditorRevealType.InCenter;

var inCenterIfOUtsideViewport = Vscode.TextEditorRevealType.InCenterIfOutsideViewport;

var TextEditorRevealType = {
  atTop: atTop,
  $$default: $$default,
  inCenter: inCenter,
  inCenterIfOUtsideViewport: inCenterIfOUtsideViewport
};

function executeCommand(command) {
  return Vscode.commands.executeCommand(command);
}

function executeCommandWithArg(command, arg) {
  return Vscode.commands.executeCommand(command, arg);
}

function registerCommand(name, callback) {
  return Vscode.commands.registerCommand(name, callback);
}

var Commands = {
  executeCommand: executeCommand,
  executeCommandWithArg: executeCommandWithArg,
  registerCommand: registerCommand
};

function activeTextEditor(param) {
  return Caml_option.undefined_to_opt(Vscode.window.activeTextEditor);
}

function createStatusBarItem(alignment) {
  return Vscode.window.createStatusBarItem(alignment);
}

function onDidChangeActiveTextEditor(listener) {
  return Vscode.window.onDidChangeActiveTextEditor(listener);
}

function showInformationMessage(message) {
  return Vscode.window.showInformationMessage(message);
}

function showQuickPick(items, options) {
  return Vscode.window.showQuickPick(items, options);
}

var $$Window = {
  activeTextEditor: activeTextEditor,
  createStatusBarItem: createStatusBarItem,
  onDidChangeActiveTextEditor: onDidChangeActiveTextEditor,
  showInformationMessage: showInformationMessage,
  showQuickPick: showQuickPick
};

var Vscode$1 = {
  Commands: Commands,
  $$Window: $$Window
};

var ExtensionContext = {};

var Position = {};

var $$Range = {};

var $$Selection = {};

var StatusBarItem = {};

var TextDocument = {};

var Options = {};

var TextEditor = {
  Options: Options
};

var TextEditorEdit = {};

var TextLine = {};

exports.StatusBarAlignment = StatusBarAlignment;
exports.TextEditorCursorStyle = TextEditorCursorStyle;
exports.TextEditorRevealType = TextEditorRevealType;
exports.Vscode = Vscode$1;
exports.ExtensionContext = ExtensionContext;
exports.Position = Position;
exports.$$Range = $$Range;
exports.$$Selection = $$Selection;
exports.StatusBarItem = StatusBarItem;
exports.TextDocument = TextDocument;
exports.TextEditor = TextEditor;
exports.TextEditorEdit = TextEditorEdit;
exports.TextLine = TextLine;
/* left Not a pure module */
