// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Binding$Vrc = require("./Binding.bs.js");

function activate(context) {
  console.log("Congratulations, your extension \"vrc\" is now active!");
  var disposable = Curry._2(Binding$Vrc.Vscode.Commands.registerCommand, "vrc.sayHello", (function (param) {
          return Curry._1(Binding$Vrc.Vscode.$$Window.showInformationMessage, "Hello, world!");
        }));
  var subscriptions = context.subscriptions;
  subscriptions.push(disposable);
  
}

function deactivate(param) {
  
}

exports.activate = activate;
exports.deactivate = deactivate;
/* Binding-Vrc Not a pure module */
